version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=94.228.113.42
      - DATABASE_NAME=mortech
      - DATABASE_USER=admin_1
      - DATABASE_PASSWORD=hppKD~s@S75;e=
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db-check
    restart: unless-stopped
    # Настройки логирования
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=vtb-backend"

  db-check:
    image: postgres:15
    command: >
      sh -c "
        until pg_isready -h 94.228.113.42 -p 5432 -U admin_1; do
          echo 'Waiting for database...';
          sleep 2;
        done;
        echo 'Database is ready!';
      "
    environment:
      - PGPASSWORD=hppKD~s@S75;e=
    restart: "no"
