"""add_company_field_to_vacancies

Revision ID: 0db6f72c8cdc
Revises: 924e0ba09b07
Create Date: 2025-09-06 17:42:08.108519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db6f72c8cdc'
down_revision: Union[str, Sequence[str], None] = '924e0ba09b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'company')
    # ### end Alembic commands ###
