"""add_user_profile_fields

Revision ID: 4765353b9ecc
Revises: 558e1eebdccd
Create Date: 2025-09-06 10:12:56.749320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4765353b9ecc'
down_revision: Union[str, Sequence[str], None] = '558e1eebdccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    employment_type_enum = sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'FREELANCE', 'INTERNSHIP', name='employmenttype')
    employment_type_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('desired_salary', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('ready_to_relocate', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('employment_type', employment_type_enum, nullable=True))
    op.add_column('users', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('work_experience', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work_experience')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'education')
    op.drop_column('users', 'employment_type')
    op.drop_column('users', 'ready_to_relocate')
    op.drop_column('users', 'desired_salary')
    op.drop_column('users', 'about')
    op.drop_column('users', 'location')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    
    # Drop enum type
    employment_type_enum = sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'FREELANCE', 'INTERNSHIP', name='employmenttype')
    employment_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
