"""add_benefits_column_to_vacancies

Revision ID: 924e0ba09b07
Revises: 4765353b9ecc
Create Date: 2025-09-06 15:20:25.377907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924e0ba09b07'
down_revision: Union[str, Sequence[str], None] = '4765353b9ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('benefits', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'benefits')
    # ### end Alembic commands ###
