"""add strengths weaknesses missing_skills brief_reason to resume_analyses

Revision ID: edbe5fb67599
Revises: b9113a660d76
Create Date: 2025-09-08 22:50:05.149647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbe5fb67599'
down_revision: Union[str, Sequence[str], None] = 'b9113a660d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_analyses', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('resume_analyses', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('resume_analyses', sa.Column('missing_skills', sa.JSON(), nullable=True))
    op.add_column('resume_analyses', sa.Column('brief_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analyses', 'brief_reason')
    op.drop_column('resume_analyses', 'missing_skills')
    op.drop_column('resume_analyses', 'weaknesses')
    op.drop_column('resume_analyses', 'strengths')
    # ### end Alembic commands ###
