"""remove_reviewed_status_from_database

Revision ID: ffd9cfd844e1
Revises: 0db6f72c8cdc
Create Date: 2025-09-06 18:10:43.924929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd9cfd844e1'
down_revision: Union[str, Sequence[str], None] = '0db6f72c8cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
